### ISSUE TITLE
User Story

### ISSUE THREAD

**Issue by benfehr** [benfehr/My-First-Agile-Project#6]
As a **site admin** I can **create a blog section** so that **users can write suggestions and give feedback**

# Acceptance Criteria

* A clear new section to write concerns
* Must have a text box
* Must have a submit button
* Must have a page with the other users suggestions

# Tasks

- [ ] Create the html and css for the new section
- [ ] Make sure it matches the websites current look
- [ ] Test the feature
- [ ]
